# For usage instructions see /config/sara/README.md
'USA':
    symptoms:
        # Key is the symptom name as it will appear to the user
        'Cough':
            # The value specified here is the threshold value for the particular symptom
            # values greater than or equal to this value are considered to be symptomatic
            # Useable values for type are [FloatSymptom, IntegerSymptom, or BoolSymptom]
            # The expected threshold value for bool_values should always be true
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 1
        'Difficulty Breathing':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 1
        'Fever':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'Used A Fever Reducer':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: false
            group: 2
        'Chills':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'Repeated Shaking with Chills':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'Muscle Pain':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'Headache':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'Sore Throat':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
        'New Loss of Taste or Smell':
            value: true
            type: 'BoolSymptom'
            threshold_operator: 'Equal'
            required: true
            group: 2
    # Jurisdictions follow a hierarchy, the hierarchy is defined by nesting jurisdictions
    # in the children: field
    children:
        'State 1':
            phone: '+13455555555'
            webpage: 'www.example.com'
            email: 'contact@example.com'
            symptoms:
                'Pulse Ox':
                    value: 90
                    threshold_operator: 'Less Than'
                    type: 'FloatSymptom'
                    required: true
            children:
                'County 1':
                'County 2':
        'State 2':
            children:
                'County 3':
                'County 4':
