development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: glyph_development
  host: '127.0.0.1'
  port: <%= ENV['CI_SQL_PORT'] %>
  username: root
  password: root

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: glyph_test
  host: '127.0.0.1'
  port: <%= ENV['CI_SQL_PORT'] %>
  username: root
  password: root
